#!/usr/bin/env node
'use strict';

/**
 * scripts/post-summary.js
 *
 * Reads data/ JSON files and posts a formatted daily P&L summary as a new
 * GitHub issue in the repository. Called from the GitHub Actions workflow.
 *
 * Required env vars:
 *   GITHUB_TOKEN       — provided automatically by Actions
 *   GITHUB_REPOSITORY  — e.g. "owner/quantbot"
 */

const fs   = require('fs');
const path = require('path');
const https = require('https');

const DATA_DIR = path.join(__dirname, '..', 'data');

function readJSON(filename, def = null) {
  try {
    const p = path.join(DATA_DIR, filename);
    if (fs.existsSync(p)) return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch { /* ignore */ }
  return def;
}

function formatPct(n) { return n !== null && n !== undefined ? (n * 100).toFixed(2) + '%' : 'N/A'; }
function formatNum(n) { return n !== null && n !== undefined ? n.toFixed(2) : 'N/A'; }

async function postIssue(token, repo, title, body) {
  return new Promise((resolve, reject) => {
    const payload = JSON.stringify({ title, body });
    const [owner, repoName] = repo.split('/');
    const opts = {
      hostname: 'api.github.com',
      path:     `/repos/${owner}/${repoName}/issues`,
      method:   'POST',
      headers: {
        'Content-Type':    'application/json',
        'Content-Length':  Buffer.byteLength(payload),
        'Authorization':   `Bearer ${token}`,
        'User-Agent':      'Quantbot/1.0',
        'Accept':          'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
    };
    const req = https.request(opts, res => {
      let data = '';
      res.on('data', d => { data += d; });
      res.on('end', () => resolve({ status: res.statusCode, body: data }));
    });
    req.on('error', reject);
    req.write(payload);
    req.end();
  });
}

async function main() {
  const token = process.env.GITHUB_TOKEN;
  const repo  = process.env.GITHUB_REPOSITORY;
  if (!token || !repo) {
    console.error('Missing GITHUB_TOKEN or GITHUB_REPOSITORY');
    process.exit(1);
  }

  const perf    = readJSON('performance.json', {});
  const insights = readJSON('insights.json', []);
  const opts    = readJSON('optimizations.json', []);
  const state   = readJSON('state.json', {});

  const latestInsight = insights[insights.length - 1] || {};
  const latestOpt     = opts[opts.length - 1] || {};

  // Collect what changed today
  const todayChanges = (opts || [])
    .filter(o => o.timestamp && o.timestamp > new Date(Date.now() - 86400000).toISOString())
    .flatMap(o => (o.changes || []).map(c => `\`${c.key}\`: ${c.before} → ${c.after} — _${c.reason}_`));

  const capital  = state.capital  || perf.capital  || '?';
  const peak     = state.peakCapital || perf.peakCapital || '?';
  const drawdown = typeof capital === 'number' && typeof peak === 'number'
    ? ((peak - capital) / peak * 100).toFixed(2) + '%' : 'N/A';

  const body = `## 📊 Quantbot Daily Summary — ${new Date().toUTCString()}

| Metric | Value |
|---|---|
| **Capital** | \$${typeof capital === 'number' ? capital.toFixed(2) : capital} |
| **Peak Capital** | \$${typeof peak === 'number' ? peak.toFixed(2) : peak} |
| **Drawdown** | ${drawdown} |
| **Win Rate (last 20)** | ${formatPct(perf.winRate)} |
| **Profit Factor** | ${formatNum(perf.profitFactor)} |
| **Avg Win** | \$${formatNum(perf.avgWin)} |
| **Avg Loss** | \$${formatNum(perf.avgLoss)} |
| **Total Trades** | ${perf.totalTrades || 'N/A'} |
| **Mode** | ${state.mode || 'N/A'} |

### 🤖 AI Changes Today (${todayChanges.length})
${todayChanges.length > 0 ? todayChanges.join('\n') : '_No parameter changes in last 24h_'}

### 🔍 Latest Deep Insight (Layer 3)
${latestInsight.biggestPattern
  ? `**Pattern:** ${latestInsight.biggestPattern}\n\n**Structural suggestion:** ${latestInsight.structuralImprovement || 'N/A'}`
  : '_No deep analysis yet — needs 30+ trades_'}

### 🏆 Best Instruments
${(perf.bestInstruments || []).join(', ') || 'N/A'}

### 📉 Worst Instruments
${(perf.worstInstruments || []).join(', ') || 'N/A'}

---
_Generated by Quantbot at ${new Date().toISOString()}_
`;

  const title = `📈 Quantbot Daily Summary — ${new Date().toISOString().slice(0, 10)}`;

  const result = await postIssue(token, repo, title, body);
  if (result.status === 201) {
    console.log('Daily summary issue posted successfully');
  } else {
    console.error('Failed to post issue:', result.status, result.body);
    process.exit(1);
  }
}

main().catch(e => { console.error(e); process.exit(1); });
